### ISSUE TITLE
feature request: get information of all cards (filter) to use in functions

### ISSUE THREAD

**Issue by strages** [websitesfortrello/trelew#10]
i would love to use this application to output or input information into other functions in the terminal. How would i go about that?

**Comment by fiatjaf** [comment]
This is not in the scope of this project. Creating a simple Trello API client that writes to STDIN is much easier than what trelew is trying to achieve, but should be another project.

However, if you want Trello data output to the terminal, you could probably just use `curl` or other terminal HTTP client.
