### ISSUE TITLE
just wanted to say-- awesome work!  This is so cool.

### ISSUE THREAD

**Issue by mikermcneil** [websitesfortrello/trelew#15]
@fiatjaf My team has a huge Trello board that takes a long time to load, so I've been looking for something like this for a long time.  I just stumbled across this repo after checking out http://webapps.stackexchange.com/questions/85141/quick-add-card-in-trello-from-anywhere-similar-to-todoist/88514#88514, and all I can say is wow!  `trelew` is everything I could have hoped for, plus more things.  Great work 👍

**Comment by fiatjaf** [comment]
Thank you, those were part of my motivations for writing it too. I'm glad it's working for you, but at the sime sorry to deliver incomplete work, as you saw in https://github.com/websitesfortrello/trelew/issues/16.
