### ISSUE TITLE
Check Node version if not 4.0+

### ISSUE THREAD

**Issue by dthree** [websitesfortrello/trelew#2]
It would probably be pretty easy to check and do a graceful message if the Node version is below 4.0, instead of it throwing an ES6 syntax error. You could do this by having an <4.0 compatible first page that then loads the rest of the code after the check.

Just an idea.

**Comment by fiatjaf** [comment]
What do you mean by "first page"? You mean a <4.0-compatible file that then requires the other files aftr a check? Will it work? I'll try.

**Comment by dthree** [comment]
Nice handling! :fire:
