### ISSUE TITLE
how to get into boards, lists or cards that have spaces in the names?

### ISSUE THREAD

**Issue by strages** [websitesfortrello/trelew#9]
the title says it all?

btw i need to always specify card "cardtitle" or board "boardtitle" instead of just the name of the card,board,list etc

**Comment by fiatjaf** [comment]
What do you mean by "I need to always specify cardtitle"? Specify where? Why?

The boards, lists and cards have their names slugified, so spaces are turned into "-". For information about the exact card name, `help card`,  `help list` and `help board` will show you a list of alternatives.
